### PR TITLE
Adding build number constant for Debugging

### PR DESCRIPTION
**Pull request by detournemint**
solves #15

### CODE REVIEW

**Comment by detournemint** [comment]
@getify Is this good or were you thinking something else?

**Comment by getify** [comment]
Oh goodness... I didn't see this PR until just now. Notification failure. I just committed a similar change closing #15 about an hour ago. So sorry, should have seen this and just accepted yours. Big thanks for pitching in!

**Comment by getify** [comment]
And actually, I think i'll kinda cherry pick some of your approach here to improve what I commited.

**Comment by getify** [comment]
There, merged your changes with mine to get the best of both worlds. Thanks! :)

**Comment by detournemint** [comment]
:+1:

**Pull request merged**
